### ISSUE TITLE
All lanes have no arrow signs if left-handed driving is enabled

### ISSUE THREAD

**Issue by JustinCheng12345** [joaofarias/csl-traffic#1]
![2015-03-26_00001](https://cloud.githubusercontent.com/assets/5191863/6841635/3f6a0e98-d3c8-11e4-8f0e-58518a8fa563.jpg)

Also test by using starting a new save with only this mod enabled.

**Comment by joaofarias** [comment]
Hi. I'm sorry for taking so long to answer. This issue must have gone under the radar :)

I'm working on it and should be fixed in the next update. It's not related to left-hand driving, though.
