### ISSUE TITLE
Terrain height conflicts with RC tool

### ISSUE THREAD

**Issue by originalfoo** [joaofarias/csl-traffic#10]
(just creating separate ticket for this)

On high terrain, the RC tool breaks in two ways...

First, above a certain altitude the overlays do not appear.

Second, higher still and the tool ceases to work completely (the UI for selecting vehicle restrictions does not even show).

Another user has also run in to this bug on a mountainous map; likely that more people will run in to same problem as they install more complex maps.

**Comment by originalfoo** [comment]
![screenshot 1](https://cloud.githubusercontent.com/assets/1386719/7666352/3b0397d6-fbda-11e4-9c40-90763646b68b.jpeg)

**Comment by joaofarias** [comment]
Fixed for next release.
