### ISSUE TITLE
Question: Save button on Options screen

### ISSUE THREAD

**Issue by originalfoo** [joaofarias/csl-traffic#11]
Is it necessary to Save on the options screen? I imagine most users might not spot the button as all similar UI commits on change (eg. main game Options screen).

**Comment by joaofarias** [comment]
The options panel is something I really need to improve in the future (internally more than in-game) so I'll leave this change for when I get to it.

**Comment by joaofarias** [comment]
I took note of this. Closing to clean the issues area.
