### ISSUE TITLE
Apparently T++ adds this thing under the map?

### ISSUE THREAD

**Issue by originalfoo** [joaofarias/csl-traffic#14]
I've seen it myself in the map / asset editor, but someone on reddit just proclaimed that this thing is caused by T++:

http://imgur.com/IouUWzT

Reddit url: http://www.reddit.com/r/CitiesSkylines/comments/369anb/terraforming_went_bad_suddenly_found_this/

**Comment by joaofarias** [comment]
Yeah, someone pointed it out to me on steam, a few days ago. When I clone a prefab (be it road, vehicle, whatever) they are created in-game and, apparently, show up in there. I'll try to move them further down to avoid being seen.

However, there is some weird stuff on that screen that I don't even recognize so it's possible that the same happens with custom assets.

**Comment by originalfoo** [comment]
It would also be worth moving them to the edge of map, and ideally making them invisible if that's at all possible. In another post where I first heard about them, someone was saying that they cause weird things to happen if roads or metro are routed over them. What would happen if you deleted them once finished cloning prefabs?

**Comment by joaofarias** [comment]
I can't answer any of your questions with 100% certainty. I'll need to try it out and find the best option.

**Comment by joaofarias** [comment]
Fixed for next release.
