### ISSUE TITLE
Better beziers on lane routing

### ISSUE THREAD

**Issue by originalfoo** [joaofarias/csl-traffic#18]
Image (via reddit) showing several issues with current curves:

![255710_screenshots_2015-05-20_00001](https://cloud.githubusercontent.com/assets/1386719/7729193/5f6d812a-ff0b-11e4-8d46-c227a1afd70b.jpg)

Straight segment intersections are particularly grim (although there's a curved one near bottom of image that also goes a bit weird).

There was a discussion about using the intersection of the angles of the road in relation to each other or centre of intersection as the point to set the bezier - possibly that would help in these situations?

**Comment by originalfoo** [comment]
I've also asked for a save game from the person who took that screenie - as I don't see any traffic lights causing those tailbacks.

source link http://www.reddit.com/r/CitiesSkylines/comments/36m2nl/look_little_timmy_its_a_traffic_miracle/

EDIT: Actually, there are traffic lights and everything was working perfectly for the end user.

**Comment by joaofarias** [comment]
Someone had already proposed that on the steam discussions. That would improve some curves but would make others even worse. I will try to improve them when I get some time, but I'm not sure that's the best option.
