### ISSUE TITLE
Compatibility issues with this and other mods that replace tools.

### ISSUE THREAD

**Issue by RosaryMala** [joaofarias/csl-traffic#2]
More specifically, I have a mod that replaces NetTool, and If both mods are installed, there's a high chance of your modified Transport Tool not kicking in. There's a much easier way to modify the tools, which I use, which should give less compatibility issues. I'll submit a pullreq soon that implements it.

**Comment by joaofarias** [comment]
Comments are on the pull request https://github.com/joaofarias/csl-traffic/pull/3
