### ISSUE TITLE
Bus stops freak near intersections?

### ISSUE THREAD

**Issue by originalfoo** [joaofarias/csl-traffic#28]
> I'm not quite sure if this belongs here, if it is the wrong place, please accept my sincere apologies. 
> The reason I downloaded this mod in the first place was that I wanted to have zoneable pedestrian roads and the original mod that provided only this functionality was taken down.
> I already had the Traffic Manager mod installed (I used it to heavily mod all my intersections to look nicer and to get the traffic sorted as early as possible) so I was very happy to see that you joined forces and made the mods work in parallel.
> 
> However, I noticed that when I do the same intersection customization with Trafic++ (every lane on basically every intersection), that many buses started to take extremely weird routes because, as it seems, they are no longer abe to go straight if the stop is too close to the intersection and the right lane only allows for right turns.
> 
> I have checked with the traffic manager in a different savegame and the buses simply disobey the rules and go straight on a right-turn-only lane ;-) (which in this case is very good for me).
> As it is not possible to use the lane changes in Taffic Manager if Traffic++ is enabled in the content manager, I find myself in a dilemma: I want zoneable pedestrian paths, but also the Traffic Manager mod behaviour as described above.
> 
> Currently, I favour not having the pedestrian paths. Would it be possible to put the pedestrian path logic into a seperate mod again? All answers/any help is greatly appreciated! :-)

source: http://steamcommunity.com/workshop/filedetails/discussion/409184143/613956964603725678/#p2

**Comment by joaofarias** [comment]
It's working fine. There's no node before the intersection to allow the bus to change lane to avoid having to turn right. That's just how the game is set up. Can't do anything about it.
