### ISSUE TITLE
T++ eating FPS in ghost mode

### ISSUE THREAD

**Issue by originalfoo** [joaofarias/csl-traffic#32]
I can imagine some FPS chompage in normal mode, due to extra pathfinding checks, but apparently ghost mode is also eating some FPS...

http://steamcommunity.com/app/255710/discussions/0/613958868358784461/

**Comment by joaofarias** [comment]
Answered in the discussion. Will investigate soon.

**Comment by joaofarias** [comment]
Will be fixed in next release.
