### ISSUE TITLE
Null reference error / no roads but pipes?

### ISSUE THREAD

**Issue by cskiwi** [joaofarias/csl-traffic#4]
since the update 2 hours ago (~2:00 PM, Friday, April 3, 2015, GMT+2) the mod stopped working. when creating a road it made water pipes, but still zonable. 

Then from the 2k4 city upgrade I got null reference errors. Any way to fix this or revert to the prev version? because the options button is also gone so no way to enable ghost mode :/

**Comment by joaofarias** [comment]
Hi cskiwi.
I haven't had the chance to test that update and the current version of Traffic++ may not be compatible. However, the fix I'm working on should be.

What do you mean by "2k4 city upgrade" and what version do you want me to revert to?

**Comment by cskiwi** [comment]
Whey your city reaches 2k4 population ;) then the null references started.

And running version 1.0.6b ( ran 1.0.7, and reverted)

**Comment by joaofarias** [comment]
Hi cskiwi,

Have you tried with the latest update yet?

**Comment by cskiwi** [comment]
Yea i've tried it very short, but won't be able to test it fully until Tuesday.
But it seems to work great!

**Comment by joaofarias** [comment]
It's been a week so I'm assuming this is solved. Feel free to reopen if not.
