### ISSUE TITLE
Null object error, many textures missing, all bridges dissapeared

### ISSUE THREAD

**Issue by originalfoo** [joaofarias/csl-traffic#42]
Not sure if this is T++ related or just lack of RAM...

https://gist.githubusercontent.com/aubergine10/5995898e5a3d5913ef38/raw/T++%20bug

I'd changed T++ options:
- Disabled Realistic Speeds
- Disabled Enhanced AI
- Prevent Despawn was disabled already (I've never enabled it)

Loaded game, and on start of game got the null object error. Noticed that all road textures were missing (including normal roads) and bridges were missing (normal highway bridges).

I have a strong suspicion that it was lack of RAM, as I had screen recording software open but not recording (first time trying to screen record in game). I noticed that the screen recorder had quit by the time the save had loaded.

Other things I'd changed since last game: Unsubscribed about 500 workshop assets (none related to roads or bridges) - partial list here: http://steamcommunity.com/sharedfiles/filedetails/?id=449978312

**Comment by originalfoo** [comment]
Just realised that I'd also recently installed Improved Public Transport - I hadn't activated it in Content Manager but looks like that could be a culprit!

**Comment by joaofarias** [comment]
Something broke but I can't find out what - it doesn't seem to have been T++. Let me know what you find on this.

**Comment by originalfoo** [comment]
I'm running tests again with similar system environment (screen recording app running) but with IPT disabled, will see what happens.

**Comment by originalfoo** [comment]
Tried everything I can think of - verify cache, changed download region, different screen resolutions...

Still get this - all highway bridges disappear, none of the roads are textured, no buildings visible on map, game time frozen.

![region capture 2](https://cloud.githubusercontent.com/assets/1386719/7852862/fb50d550-04fc-11e5-8d14-c2657d9ef4df.png)

Same sort of errors as in log file posted earlier.

**Comment by originalfoo** [comment]
Apparently it was a bug in Traffic Manager, something to do with traffic lights and the HumanAI.

http://www.reddit.com/r/CitiesSkylines/comments/37mnam/help_any_idea_why_this_happen/
