### ISSUE TITLE
RC button hides/breaks Terraform Tool button

### ISSUE THREAD

**Issue by originalfoo** [joaofarias/csl-traffic#43]
Not been able to reproduce this one, but here is details from user:

user said:

> Since your last update, it seems that your UI icon "took" Terraform Tool's icon place. I can't find the icon to terraform, is it normal or not?

I asked some details, user replied:

> I play at 1920*1080. I have 3 icons on the right : budget, politics, and road customizer. I had 3 icons too before : budget, politics, and terraform.
> 
> So I guess Traffic++ icon took Terraform's icon place.
> 
> I also noticed that those f*cking seagulls are back to achieve my ears.
> I used (and still use) ARIS mod to remove those damn birds.
> 
> So your guess that something might be conflicting with mods and prevent them to load is credible.
> 
> Tell me if I need to give more informations.

I asked:

> @Sharblue are you using a custom skin (like Sapphire UI stuff)? I'm using 1600x900 resolution (my gfx card can't handle 1920x1080) and not able to reproduce problem :/ As for the seagulls, I'd check with Soda (ARIS mods author) to see if he's heard about any similar issues with that mod not working; his mods are generally very reliable. What other mods do you have installed? Also, is there anything in your log file (see here for log file locations: http://steamcommunity.com/workshop/filedetails/discussion/409184143/613958868376457349/ ). 

User replied:

```
Well, tbh, I have a huge list of active mods.

Automatic Bulldoze
Enable achievements
Ambiant occlusion
Sun shaft
Tree brush
Post process FX
All areas purshasable (25)
Extanded public transport UI (I feel he's the guilt...)
Traffic report tool
Automatic line color
Toggle traffic lights (work great, even with Traffic Manager)
Simple Clock
Disable clouds
Slow speed
Editor terraform tool
Area enabler (starter)
Terraform tool
ARIS Skylines Overwatch
ARIS Remove Seagulls
Traffic Manager
Improved Public Transport
Chirpy Banner
Mod Corral
Automatic emptying
District UI Tweaks
Multi tracks stations enabler
City Vitals Watch
Traffic++ (with road customizer tool checked)
Extended building information tool
Precision Engineering
Better SMAA
One way street arrow
Building Eye dropper tool
```

Log file (link to download is directly below the bold filename text): http://uptobox.com/l3rlqledvpbv

Discussion URL: http://steamcommunity.com/workshop/filedetails/discussion/409184143/613956964601171090/?tscn=1432747271#p1

**Comment by originalfoo** [comment]
I've suggested he look to remove Mod Corral - it adds toolbar button and also known to break since 1.1.0 patch.

**Comment by joaofarias** [comment]
The user found out it was the chirp corral. Closing this.

**Comment by originalfoo** [comment]
FAQs updated to mention this.
