### ISSUE TITLE
Save game load error

### ISSUE THREAD

**Issue by originalfoo** [joaofarias/csl-traffic#47]
I'm fairly certain that this isn't to do with T++ or TM, however if you are able it would be useful if you could cast your eyes over it...

Save A: this one crashes on load

http://steamcommunity.com/sharedfiles/filedetails/?id=451590687

Save B: this earlier save loads ok

http://steamcommunity.com/sharedfiles/filedetails/?id=451592413

Both are the same map/game. Save B was created a day or two before Save A. When loading Save A all kinds of breakage happens, such as that mentioned in closed issue #42 

If there's some way to determine what is actually going wrong, it would be very useful as I can report back to others who are having same issue.

**Comment by joaofarias** [comment]
None of them works for me. Can you send me your logs from running both saves?

**Comment by originalfoo** [comment]
Will do.

BTW, it's looking increasingly likely that the issue is something to do with workshop vehicle assets being unsubscribed or missing - particularly those on public transport. Seems the game doesn't know how to handle them missing when save is loaded.

Will try and get the logfiles now.

**Comment by joaofarias** [comment]
That was my first thought but I tried disabling the ones I'm using on my saves and it still worked. However, I'm not using any on public transport. They're all resident vehicles. So that might be it.

**Comment by originalfoo** [comment]
Save A log file: https://gist.github.com/aubergine10/da3a510fd9e27c8e63db

**Comment by originalfoo** [comment]
Save B log file: https://gist.github.com/aubergine10/f48c853c6510719c3523

**Comment by originalfoo** [comment]
Got several more users reporting that re-subscribing workshop vehicle assets fixes the error. Looks like CO/Paradox didn't test what would happen when people unsubscribe vehicles :/

I don't know if this is related to the other errors that people are getting - eg. flying vehicles, stalling vehicles, etc...

**Comment by joaofarias** [comment]
I wanted your logs to compare with mine, to see if I'd find something off, but didn't produce any results.

I've tried subscribing to a few buses, police cars and garbage trucks. Played a bit, saved, disabled them in the assets panel, but the game still loaded fine. Really don't know what's going on... :/

**Comment by originalfoo** [comment]
Lots of people are getting this error, but many don't have T++ and some don't even use mods.

Looking increasingly likely that it's something to do with broken assets (usually vehicles, but sometimes buildings too) - often cause by other mods (and formerly T++ prior to bug fix) changing AIs in asset editor.

Possible mod culprits include Enhanced Building Capacity, No Despawn Mod, IPT.

**Comment by joaofarias** [comment]
I'll close this one as it's not related with T++. Feel free to reopen, otherwise.
