### ISSUE TITLE
Install manually

### ISSUE THREAD

**Issue by lucasfeijo** [joaofarias/csl-traffic#5]
I know this is not exactly a discussion to be held here, but I tried to install this mod manually moving it into
 ~/Library/Application Support/Colossal Order/Cities_Skylines/Addons/Mods/CSL-Traffic
and the game doesn't show it in the mod list. What am I doing wrong?

**Comment by joaofarias** [comment]
Hi Lucas,

Have you moved the code or have you built it and moved the dll?
I suppose it was the latter, in which case I don't know what you're doing wrong.

**Comment by lucasfeijo** [comment]
I thought the game compiled the code for me runtime. So I haven't.
I just copied a stable commit of the mod and moved it to that directory.

On Mon, Apr 6, 2015 at 4:12 PM, joaofarias notifications@github.com wrote:

> Hi Lucas,
> 
> Have you moved the code or have you built it and moved the dll?
> I suppose it was the latter, in which case I don't know what you're doing
> wrong.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/joaofarias/csl-traffic/issues/5#issuecomment-90203051
> .

## 

_Lucas Feijó_

**Comment by joaofarias** [comment]
Ah, in that case you must create another folder called "Source" and put the code inside. However, I'm not sure how the game compiler handles the references to other libraries, so I'm not sure that it's going to work.

**Comment by lucasfeijo** [comment]
You're right, I got errors trying to reference ColossalFramework. I might
need to compile it first. That's quite a bit of work, but I'll do it to
rescue my corrupted saves.

On Mon, Apr 6, 2015 at 4:23 PM, joaofarias notifications@github.com wrote:

> Ah, in that case you must create another folder called "Source" and put
> the code inside. However, I'm not sure how the game compiler handles the
> references to other libraries, so I'm not sure that it's going to work.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/joaofarias/csl-traffic/issues/5#issuecomment-90205018
> .

## 

_Lucas Feijó_

**Comment by joaofarias** [comment]
It would have been simpler to just ask me for it.

I'm closing this now as your problem is solved. Good luck.
