### ISSUE TITLE
Duplicate road prefabs ?!

### ISSUE THREAD

**Issue by originalfoo** [joaofarias/csl-traffic#50]
source: http://steamcommunity.com/workshop/filedetails/discussion/409184143/615085406663557559/

Snippet of problem:

```
Small Busway OneWay Tunnel: Small Busway OneWay Tunnel: Duplicate prefab name
Small Busway OneWay Slope: Small Busway OneWay Slope: Duplicate prefab name
Small Busway Bridge: Small Busway Bridge: Duplicate prefab name
Small Busway Elevated: Small Busway Elevated: Duplicate prefab name
Small Busway Tunnel: Small Busway Tunnel: Duplicate prefab name
Small Busway Slope: Small Busway Slope: Duplicate prefab name
Small Busway OneWay Bridge: Small Busway OneWay Bridge: Duplicate prefab name
Small Busway OneWay Elevated: Small Busway OneWay Elevated: Duplicate prefab name
```

Log file: https://gist.github.com/anonymous/36109a530a19b4830c58

Almost as if the plugin is re-initialising (looking at code it should already handle that scenario...?) or there's two instances running?

**Comment by joaofarias** [comment]
This is a bug from the ghost mode introduced with the new roads. When in ghost mode, the prefabs are not added to the customPrefabs list that prevents duplicates.

I'm putting together a few bugfixes like this that I've been "collecting" throughout the week and will release tomorrow night or monday morning.

**Comment by joaofarias** [comment]
Fixed.
