### ISSUE TITLE
Tunnel bus lanes still used by other vehicles

### ISSUE THREAD

**Issue by originalfoo** [joaofarias/csl-traffic#51]
> When I create a buslane (sidelane or dedicated two-lane) in a tunnel, the others cars will also use the buslane is if it was a normal lane. I only found this problem when I create a tunnel.

http://steamcommunity.com/workshop/filedetails/discussion/409184143/615085406664212061/?tscn=1433025676#c615085406665616540

**Comment by originalfoo** [comment]
Seems to happen on non-tunnel bus roads as well:

https://www.reddit.com/r/CitiesSkylines/comments/37zmgq/passenger_vehicles_using_traffic_bus_lanes/

**Comment by joaofarias** [comment]
Hmm.. I'm starting to think that the AI isn't being replaced. I'll put some more debug info in the next release to try to figure this out (and the flying vehicles).

**Comment by originalfoo** [comment]
I thought it was the pathfinder that deals with lane selection, not the AI?

**Comment by joaofarias** [comment]
But it needs my AI to call my pathfinder ;)

**Comment by joaofarias** [comment]
Maybe it wasn't the lack of a custom AI. It's supposed to be fixed but I'll wait for confirmation before closing this.

**Comment by originalfoo** [comment]
I've not seen any reports of this bug since last update.
