### ISSUE TITLE
URGENT: Trucks/trains not spawning since 1st Jun update

### ISSUE THREAD

**Issue by originalfoo** [joaofarias/csl-traffic#54]
https://www.reddit.com/r/CitiesSkylines/comments/384zvw/update_traffic_bug_fix_release/crseye6

> Issue: No cargo trucks spawning into town or from factories.
> Noticed it within 10 mins of my save file, with a small town. Trucks that were in the save, just drive through my small town, but no more spawn. Created a new town, and this time l noticed no trucks at all.
> .
> I don't have any of the mod options enabled, but tried the road customizer anyways to see if it would fix it, but no dice. Even bought out the two regions and demolished my highways and re-created them. This only started when the mod updated about a hour ago.
> .
> Have the very same issue. No cargo traffic whatsoever. Taffic++ is the only mod that I have installed. No heavy traffic ban in any of my districts.
> .
> Was just playing a new city and thought it was weird no log trucks were driving through my forestry area. Hopefully it gets resolved soon
> .
> Well, this update has been a tragedy for my city. Absolutely no trucks driving around, and no cargo trains/ships are coming in (which could be because there are no trucks to pick up the cargo anyway). Hopefully this is fixed quickly
> .
> I came here because just recently my shops are running out of goods to sell. Then I noticed no cargo trains. Then I noticed no trucks! What the heck happened?

**Comment by originalfoo** [comment]
https://www.reddit.com/r/CitiesSkylines/comments/385p5o/traffic_causes_trucks_not_to_spawn/

**Comment by originalfoo** [comment]
https://www.reddit.com/r/CitiesSkylines/comments/385njw/industry_not_spawning_trucks_to_exportdeliver/

**Comment by originalfoo** [comment]
https://www.reddit.com/r/CitiesSkylines/comments/385l10/freight_has_disappeared_from_my_city_entirely/

**Comment by originalfoo** [comment]
http://steamcommunity.com/app/255710/discussions/0/615085406673669652/

**Comment by originalfoo** [comment]
http://steamcommunity.com/workshop/filedetails/discussion/409184143/613958868376457349/?tscn=1433207530#c615085406673676817

> To clarify, the problem appears to be that all newly built roads since the latest hotfix are disabling CargoTrucks on all and any applicable lanes by default. Can be worked around temporarily by manually enabling the CargoTrucks on each and every lane but as you can imagine this is pretty tedious! Existing roads should be unaffected as far as I can tell, but it's late and haven't been simming for too long.

**Comment by originalfoo** [comment]
https://forum.paradoxplaza.com/forum/index.php?threads/theres-no-cargo-transport-in-my-city.859109/

**Comment by originalfoo** [comment]
> 1. When I applied the lane split to my current city a few hours ago all cargo shipments completely stopped - ie. not one cargo truck to be seen
> 2. Once I added the forward option to the right turning lane (so: left, forward, forward/right) the situation got fixed - been playing this way for the last couple of hours and everything is fine (still using T++ and TM)

https://forum.paradoxplaza.com/forum/index.php?threads/psa-not-enough-goods-to-sell-tied-to-traffic-changing-mods-traffic-and-traffic-manager.859104/#post-19397873

**Comment by originalfoo** [comment]
http://steamcommunity.com/workshop/filedetails/discussion/409184143/613958868376457349/?tscn=1433213356#c615085406673931230

> In addition to the above, after reloading a save (due to the some unfortunate road experimentation) it appears that previously assigned lane rules re vehicle type useage suddenly becomes ignored. For example a few bridges that I've specified CargoTrucks not to use, is ignored and becomes heavily congested. So it seems existing roads (some, not all) are also affected by the bug.
> 
> EDIT: Log file and save linked: https://drive.google.com/folderview?id=0B2qQtVz8-CJFfjAzUmY0MDN2cTBTRzhGY29zYlFnYWVVX2tBZEFOb0Y4SVAyLU5TaUJuc0U&usp=sharing

**Comment by originalfoo** [comment]
http://steamcommunity.com/workshop/filedetails/discussion/409184143/613958868376457349/?tscn=1433213356#c615085406673931784

> I did some extensive simming and found that after a certain amount of time the industrial trucks and commercial vans completely stopped spawning. I've thrown the mod into ghost mode and that at least allows me to continue building my city, but I thought you should be aware of this potentially catastrophic bug.

**Comment by originalfoo** [comment]
> I don't know if anyone has any solution of common problem but suddenly no cargo ships or trains enter or even operate on the map with 4 cargo train terminals and 3 Ship terminals. While airports and Cruise ships as well as the rest of my public transportation operate normally.

http://steamcommunity.com/app/255710/discussions/0/615085406673867486/

**Comment by originalfoo** [comment]
Not sure if this was said in jest or not, but apparently no cargo ships either!

**Comment by joaofarias** [comment]
Fixed. Instructions to fix games that where saved with this bug are here: http://steamcommunity.com/workshop/filedetails/discussion/409184143/613958868376457349/#c615085406675158903

Edit: I'll leave this open until confirmation that the lack of trains is due to lack of trucks.

**Comment by originalfoo** [comment]
Groups notified of bugfix and subsequent steps to take:
- [x] Reddit
- [x] Steam
- [x] Paradox
- [x] Troubleshooting guide

**Comment by originalfoo** [comment]
I think we need to rethink the release process - maybe do that thing where we create a separate Workshop page for beta test version of the mod so that intrepid mayors can try the new releases first and report back prior to the main T++ mod being updated. Would obviously require some extra code as we'll end up with some users having two versions of the mod installed, but IMHO it will be much better to have wider test group making sure there are no buglets prior to rolling out changes to >80,000 users.

**Comment by joaofarias** [comment]
Yes, definitely. I want to start that with the new performance-focused version. It will be a friends-only mod to avoid people that want the latest thing but are not interested in giving feedback.

So, the new process will be:
- Release update on closed beta version on monday/tuesday
- Fix any subsequent bugs
- If everything's okay, release to the public on thursday/friday

Sounds good?

**Comment by originalfoo** [comment]
Yup :)

**Comment by originalfoo** [comment]
Multiple confirmations that the cargo no spawn bug is fixed :)
