### ISSUE TITLE
Lane changer not present

### ISSUE THREAD

**Issue by Elmuti** [joaofarias/csl-traffic#58]
#### Issue

I don't have to option to change/edit lanes at all. The option is taken away from Traffic Manager but Traffic++ itself doesn't hand me any editing options anywhere. The icon on the far right of the toolbar is Cimtographer.
#### Screenshot

http://puu.sh/idITc/121eb90c4d.png

**Comment by originalfoo** [comment]
Did you enable the Road Customiser in Content Manager > Mods > Traffic++ > Options?

**Comment by Elmuti** [comment]
Oh I did not know you need to enable it, should've done more research. Yeah it's all fine now, thanks!
