### ISSUE TITLE
Intersection lane routing for new roads not working

### ISSUE THREAD

**Issue by originalfoo** [joaofarias/csl-traffic#6]
Steps to reproduce:

Out in the middle of nowhere, draw a new cross roads, ie. a + shape, with those roads not connecting to anything other than the intersection at the centre of cross roads.

Do some random lane routing - road arrows don't update

Exit edit mode, then go back in to edit mode and the custom routing was not stored.

What should happen:

Lane arrows should update when creating new routes, the routes should be saved.

**Comment by joaofarias** [comment]
Thank you.

I was able to reproduce the issue but haven't investigated further yet. Will do in the coming days.

**Comment by joaofarias** [comment]
I've located and fixed this issue. I'll close it when I commit the fix.
