### ISSUE TITLE
Performance Improvements

### ISSUE THREAD

**Issue by Nefarion** [joaofarias/csl-traffic#60]
**This is a WIP**, i am writing down everything i find regarding Performance.
- [ ] Buffer objects accessed by array indexes
  - [CustomPathFind.cs:184](https://github.com/joaofarias/csl-traffic/blob/f7fde6a9b08d2769fc2d710cbbb419a1ba52e212/CSL-Traffic/PathFinding/CustomPathFind.cs#L184) for example

(Comments welcome ofcourse)

**Comment by originalfoo** [comment]
@joaofarias would it be worth creating a new branch and uploading your current WIP on the updated pathfinding code?

**Comment by joaofarias** [comment]
@aubergine10 I've done that yesterday. It's the optimizations branch. ;)

@Nefarion Are you working on fixing that or are you just identifying potential performance issues?

**Comment by Nefarion** [comment]
@joaofarias Doing both,
will update the list as i go on :)
see #61 for a start
