### ISSUE TITLE
Incompatibility with European Building Unlocker mod

### ISSUE THREAD

**Issue by originalfoo** [joaofarias/csl-traffic#68]
> This seems to break with EuropeanBuildingsUnlocker; Using that mod, With native off (and non-native on), to build a european city in a non-european biome, and turning on the lane changing interface, nothing was visible on the toolbar except the road button (empty) and the Traffic++ editing button - no zoning, district, placement buttons - just an otherwise empty toolbar.

via Xgkkp here: http://steamcommunity.com/sharedfiles/filedetails/?id=409184143

**Comment by originalfoo** [comment]
BloodyPenguin replied: 

> hi! It's just E.B.Us random bug. It's not a conflict. I'm aware of the problem and already spent much time trying to fix it. At this moment to workaround the issue you need to go back to main menu and reload the save game. If that doesn't help, repeat.

**Comment by ndevenish** [comment]
I actually solved this the easy (cheating) way by:
- Removing EuropeanBuildingsUnlocker
- Re-creating the custom map in Europe zone

**Comment by joaofarias** [comment]
Closing this since it's not a conflict.
