### ISSUE TITLE
Idea: Regarding the future AI improvement. Add 2 options!

### ISSUE THREAD

**Issue by Rafario448** [joaofarias/csl-traffic#75]
I read in reddit that in the future update will improve AI!

aubergine10 replied a user that the AI will calculate their pathfinder two times: when they get out of home and when they find themselves stuck on a traffic jam.

I suggest adding more options at enhanced AI so we can configure with type of vehicle will have this new behavior and when.
If their consider choosing the best lanes and the best routes ONLY when they start their journey, the new feature should not have a huge impact in performance. Let the option " Allow vehicles change pathfinder during the travel" only to those that want to make the game more realistic.

sry for bad english.

**Comment by originalfoo** [comment]
> the new feature should not have a huge impact in performance

The pathfinder and AIs are so heavily used by the game that even the slightest tweak can cause a big performance issue.

**Comment by Rafario448** [comment]
Ok, but making them recalculate their paths in the middle of a journey will just make the things worse, as they will need to take another road/lane and consider the restrictions from Road Customiser.

BTW this mod (alongside with Traffic Manager) is my fav! keep the excellent work!
I'm closing the issue. Thank you for replying.
