### ISSUE TITLE
The phantom might still lurk in ghost mode...

### ISSUE THREAD

**Issue by originalfoo** [joaofarias/csl-traffic#76]
http://imgur.com/FNE7Hs2

Noooooooooo!!

**Comment by joaofarias** [comment]
I'm pretty sure that's the some roads mod. Notice the blueprint road below the train tracks (that are also not added by T++ but by that mod).

**Comment by originalfoo** [comment]
Cool, will let people know :)

Glad you're back online, it's all been going crazy since the patch release on wednesday lol.
